name: impaktfull_ui
description: A Flutter package for Impaktfull UI components.
repository: https://github.com/impaktfull/flutter_impaktfull_ui
homepage: https://impaktfull.com
version: 0.5.0
environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.3.0"
dependencies:
  intl: ^0.18.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  lottie: ^3.0.0
  snacky: ^0.0.14
  universal_io: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/icons/
    - assets/lottie/
